### ISSUE TITLE
hi, i have problem

### ISSUE THREAD

**Issue by thedark1232** [StarChasers/OCGlasses#107]
how can I link my glasses not to the terminal, but to the terminal card? My email World1300@yandex.ru! Thank you!

**Comment by ben-mkiv** [comment]
```lua
startLinking([String:playerName])
-- this requests the player to accept the linking on its glasses (the request will be sent to all users within 64 blocks range if playerName is empty)
```

you have to sneak + press the glasses interaction key if no popup shows after calling the command
