### ISSUE TITLE
[Immersive Vehicles MOD Minecraft 1.12.2 BUG] 

### ISSUE THREAD

**Issue by Sparkzz0142** [StarChasers/OCGlasses#108]
I can't spawn vehicles. I reinstalled the mod to fix the bug but it didn't work. Please help if u know how to fix this bug, thanks for reading.

**Comment by ben-mkiv** [comment]
and how is that related to OpenGlasses?

Does the problem only occur when both mods are installed?

There has been a problem with both mods installed in the past, but that should be sorted out (see https://github.com/Starchasers/OCGlasses/issues/77 for reference)

so which mod versions are you using?

**Comment by ProsperCraft** [comment]
We are not seeing this on TownCraft ONE with both mods fully updated.
