### ISSUE TITLE
Placing down Glasses terminal crashes client and dupes item

### ISSUE THREAD

**Issue by shortybsd** [StarChasers/OCGlasses#16]
When placing down a Glasses Terminal my client will get kicked from server (Internal server error) server says http://pastebin.com/hnXHXNqs
I tried with forge, same error with a forge in place of cauldron error. Also says "[02:18:15 WARN]: Selector.select() returned prematurely 512 times in a row; rebuilding selector."
When you log back in you have the glasses terminal in your inventory along with the one you placed before crashing.
Running OpenGlasses v1.0.43 and OpenComputers v1.5.2.9
Side Note: I can access the Glasses terminal via computer just fine.

**Comment by Kubuxu** [comment]
Try new build (45)[http://starchasers.pl:8080/job/OpenGlasses/45/] from jenkins.
We didn't and won't check Bukkit compatibility.

**Comment by shortybsd** [comment]
awesome! Thank you so much, will implement right now. Any simple examples for AR Glasses to put things on the screen 2D? I'll try to update wiki once I learn it and get more acquainted with it.

**Comment by Kubuxu** [comment]
@shortybsd I have to redirect you to @marcin212.

**Comment by shortybsd** [comment]
Thanks again @Kubuxu! Works great, cauldron is ran more then forge servers. I would convert over to forge but due to instability, performance issues and have a few plugins I wrote that would have to be re-written. Thanks again for super quick fix and push.

**Comment by shortybsd** [comment]
Here is a quick demo I wrote for OpenGlasses, feel free to use it on the web site - https://gitlab.com/shortybsd/OpenComputers-Shared/blob/master/OGDemo.lua
