### ISSUE TITLE
Config option for adjusting how much power is used.

### ISSUE THREAD

**Issue by JasonUnger** [StarChasers/OCGlasses#17]
Line 308 of OpenGlassesTerminalTileEntity seems to be the place this is done? I'm not familiar with OpenComputer's arch.

Basically, whenever the terminal is powered up, it sucks the living daylights out of my power setup. Would like to lessen the amount of power required. Also respecting Creative cases would be another config item.

**Comment by marcin212** [comment]
Done

**Comment by JasonUnger** [comment]
Excellent, thanks!
