### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by SergOmarov** [StarChasers/OCGlasses#19]
Why the bridge can not determine the distance to player, and from player to objects?

**Comment by Kubuxu** [comment]
Why should it?

**Comment by Alaberti** [comment]
It might be a handy feature as part of a waypoint system I imagine, especially in a pack without a minimap or something.

**Comment by Kubuxu** [comment]
Then use OC's tablet and OC's map upgrade and waypoints.

You can calculate position then relative to the glasses interface and relative to the object.

**Comment by marcin212** [comment]
Last update contains new events http://starchasers.pl/OpenGlasses/doku.php?id=terminal
