### ISSUE TITLE
Chat commands

### ISSUE THREAD

**Issue by danshat** [StarChasers/OCGlasses#22]
Nope, I am seriously. These glasses need chat commands like in OpenPeripheral. No matter what prefix must be used (@ or $$ or ## idk) but chat commands would be nice. Through some kind of "ar_chat_command" event or something.

**Comment by magik6k** [comment]
You may try to use computronics chatbox block

**Comment by danshat** [comment]
And get all the chat spammed with your commands, yes? Show everyone your commands passwords secret data nuclear codes etc.

**Comment by marcin212** [comment]
You can use OpenComputer's tablet with Wi-Fi or LinkedCard

**Comment by marcin212** [comment]
or You can use new events: http://starchasers.pl/OpenGlasses/doku.php?id=terminal
