### ISSUE TITLE
Personalized output

### ISSUE THREAD

**Issue by MoonlightOwl** [StarChasers/OCGlasses#30]
It would be cool, if you can show different widgets to different people.
For example, to create AR-chat. Or make virtual interface with admin features, that only visible to system owner.

**Comment by ben-mkiv** [comment]
made some patch which adds a userflag to each widget, theres a release for 1.10.2 which you can test: 
https://github.com/ben-mkiv/OCGlasses/releases/

@marcin212 feel free to merge it to your repo
https://github.com/ben-mkiv/OCGlasses/commits/MC1.10.2

**Comment by ben-mkiv** [comment]
private widgets are now supported by OpenGlasses2
https://minecraft.curseforge.com/projects/openglasses2
