### ISSUE TITLE
Mod integration

### ISSUE THREAD

**Issue by SFort** [StarChasers/OCGlasses#32]
It would be amazing to see integration with [Baubles](https://github.com/Azanor/Baubles) or [Cyberware](https://github.com/Flaxbeard/Cyberware)

**Comment by ben-mkiv** [comment]
i've patched 1.4.2 for 1.10.2 to support baubles + private widgets
https://github.com/ben-mkiv/OCGlasses/releases

well, finally... hope i got this right now:
there are my commits, the baubles support needed java version bump to v8, so please take also a look on the other commits. also it's my first minecraft and java project so c&c is welcome ;)
https://github.com/ben-mkiv/OCGlasses/commits/MC1.10.2

**Comment by ben-mkiv** [comment]
baubles support is now in OpenGlasses2
https://minecraft.curseforge.com/projects/openglasses2
