### ISSUE TITLE
Add OpenGL-esk triangle strip widget.

### ISSUE THREAD

**Issue by elijahlorden** [StarChasers/OCGlasses#35]
In OpenGL you can pass the renderer a list of vertices to be rendered in one call, rather than many calls for each individual triangle.  I propose a widget that takes an table of vertices in it's initializer and renders them all at once.  The table would be a simple numeric array {#, #, #, #, #, #, #, #, #}, with each set of 3 numbers representing a triangle.

**Comment by Kubuxu** [comment]
It is done in the backend.

**Comment by elijahlorden** [comment]
Is it possible for this to be directly accessible via the LUA API?

**Comment by Kubuxu** [comment]
No that I know of.

**Comment by marcin212** [comment]
Duplicate of #15

**Comment by ben-mkiv** [comment]
supported by OpenGlasses2 (custom shapes)
https://minecraft.curseforge.com/projects/openglasses2

https://github.com/StarChasers/OCGlasses/wiki/Widget_Custom2D
https://github.com/StarChasers/OCGlasses/wiki/Widget_Custom3D
