### ISSUE TITLE
Player unable to log in with openglasses on. Sponge environment.

### ISSUE THREAD

**Issue by ProsperCraft** [StarChasers/OCGlasses#39]
https://gist.github.com/ProsperCraft/5b9d1ba628f6263320a10f93a6a8acfe

##modlist- 
https://minecraft.curseforge.com/projects/towncraft

##Environment.
[16:59:01] [Server thread/INFO]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-bec74cd
    SpongeForge: 1.12.2-2611-7.1.0-BETA-3016
    Minecraft Forge: 14.23.2.2627

**Comment by mzx987** [comment]
I can confirm that my server is having the same issue. My guess is that Sponge is unable to pick up the location of the Terminal when unloaded, causing some network issue to occur with anyone wearing the glasses outside of its range.

I'm currently using the following:
SpongeForge 1.12.2-2655-7.1.0-BETA-3080
Minecraft Forge 14.23.3.2655

**Comment by ben-mkiv** [comment]
please switch to OpenGlasses2 or leave a comment here if you really need a fix and want to keep using old OpenGlasses

**Comment by ProsperCraft** [comment]
Will switch out for OG2 in TownCraft Next update.
