### ISSUE TITLE
Wiki not available: 502 bad gateway

### ISSUE THREAD

**Issue by guillaumearm** [StarChasers/OCGlasses#40]
Hi,

There is a 502 bad gateway error on https://starchasers.pl
I cannot reach http://starchasers.pl/OpenGlasses/doku.php?id=start

Where can I find the actual documentation ?

Thanks for your help.

**Comment by alucard87pl** [comment]
Looks like the site is having some certificate issues as well. I'll let them know.

**Comment by marcin212** [comment]
It is old link. New is http://minecraft.bymarcin.com/OpenGlasses/doku.php?id=start
