### ISSUE TITLE
[Suggestion] Vivecraft Support

### ISSUE THREAD

**Issue by Shazuli** [StarChasers/OCGlasses#41]
***Hi!***

I recently got a VR gear, and I noticed there is a mod for Minecraft called [Vivecraft](http://www.vivecraft.org/) that adds VR support.

OG does work no problems, but how Vivecraft renders stuff makes the hud appear on the left hand. But holding down the keybind to free the mouse changes it to "wide mode" where the hud is rendered on the whole screen. My suggestion is that HUD elements will not render until you hold the OG pointer keybind if Vivecraft is installed, then you wouldn't have a huge paperboard clued to your left hand.

![vr](https://user-images.githubusercontent.com/9884180/40585085-c0e9df64-61ac-11e8-8a82-52e12214a206.gif)

**Comment by ben-mkiv** [comment]
this can be archived with OpenGlasses2

For Example, add a modifier which sets the Alpha to 0 which is active when the HUD is inactive. so the item wont be visible.

Example:
	widget = component.glasses.addBox2D()
	alphaModifier = widget.addColor(0, 0, 0, 0)
	widget.setCondition(alphaModifier, "OVERLAY_INACTIVE", true)

More infos about Modifiers and Conditions can be found here:
https://github.com/StarChasers/OCGlasses/wiki/WidgetModifiers
https://github.com/StarChasers/OCGlasses/wiki/WidgetModifierConditions#setcondition
https://github.com/StarChasers/OCGlasses/wiki/WidgetModifierConditions#overlayactive
