### ISSUE TITLE
Graphic Error

### ISSUE THREAD

**Issue by Shazuli** [StarChasers/OCGlasses#43]
***Hi!***

I was working on a program when I noticed a graphical glitch with the 3D cube. Cubes that are made after another cube will always overlap the other, which results in a very weird image:

![2018-06-23_19 15 33](https://user-images.githubusercontent.com/9884180/41812033-5e024d1c-771b-11e8-80e7-239cb157d22a.png)

This is an image of it from the other side:

![2018-06-23_19 15 17](https://user-images.githubusercontent.com/9884180/41812042-7d2c4d46-771b-11e8-863d-9ab7e13234eb.png)

**Comment by ben-mkiv** [comment]
can you give OpenGlasses2 a try? (uses a slightly different API but iirc i sorted that bug out)

https://minecraft.curseforge.com/projects/openglasses2

**Comment by Shazuli** [comment]
This is how it looks with OG2 render:

![render](https://user-images.githubusercontent.com/9884180/44731930-94c4f000-aae4-11e8-8781-5c8386688fd6.gif)

**Comment by ben-mkiv** [comment]
thanks for testing. that almost looks like the same glitch i've noticed in my referenced issue. 
So i'll take a look into it later, but can't give any ETA right now.

**Comment by ben-mkiv** [comment]
so... this cant be solved due to the nature how the widgets are drawn. only way to affect the result is to render them in different order.
