### ISSUE TITLE
Custom3D widget not working

### ISSUE THREAD

**Issue by Antyrox** [StarChasers/OCGlasses#53]
Hello. For some reason i cant use Custom3D from OpenGlasses2.
When try to draw simple triangle it is actually drawn only in approximately 10% of attempts. In other 90% nothing is drawn. Also sometimes when i try to draw a triangle my game crashes. Here is [crash log](https://pastebin.com/2BGQJetx).

This is my test lua code : 
glassesTerminal = require("component").glasses
glassesTerminal.removeAll()

local custom = glassesTerminal.addCustom3D()
custom.addVertex(2, 4, 0)
custom.addVertex(0, 2, 0)
custom.addVertex(0, 4, 0)

custom.addColor(1, 0, 0, 0.5)
custom.setShading("FLAT")
custom.setGLMODE("TRIANGLES")

local custom = glassesTerminal.addCustom3D()
custom.addVertex(0.2, 0.4, 0)
custom.addVertex(0, 0.2, 0)
custom.addVertex(0, 0.4, 0)

custom.addColor(1, 0, 0, 0.5)
custom.addTranslation(0, 2, 0)
custom.setShading("FLAT")
custom.setGLMODE("TRIANGLES")

**Comment by ben-mkiv** [comment]
thanks for the bugreport, bug is fixed in 2.0.1 release which is now on curseforge

**Comment by Antyrox** [comment]
thanks for fixing it
