### ISSUE TITLE
[Suggestion] Hardware

### ISSUE THREAD

**Issue by Shazuli** [StarChasers/OCGlasses#54]
***Hi!***

I am sure you already have some plans for this, but here is my take on how *upgrades* should work:
Right now you take your glasses, put them on a anvil, place the desired upgrade on top of it and smack it as hard as you can until it's inside of the glasses them self. But it would be neat if it worked similar to OC's other devices such as the Tablet or Drone where you put a casing into the Electronic Assembler and thereafter put the upgrades inside. I made a picture of it for some reason:
![og feature suggestion](https://user-images.githubusercontent.com/9884180/49691136-493acd00-fb3c-11e8-8092-3d9a1fd35929.png)

And instead of been given a random address it would need a Linked Card which is the medium between the Computer and the glasses. The other pair could be inserted into a A) OG Terminal or B) a small card container you open by right clicking and placing the Linked Card inside and then put that container into ex. a Robot or Drone (Upgrade Slot)(might be tricky to use the Linked Card as receiver/transmitter directly inside a computer, so a compatibility layer that reads the Linked Card's address).

**Comment by ben-mkiv** [comment]
iirc it wasn't really possible to use the Assembler without a lot of code overhead just to make the glasses an OC device. Might look into that at some point again.

The linked card thing probably wont happen. But i've already started to make the terminal an upgrade. But this isn't finished as its still not decided how to handle linking and render location for tablets for example.

**Comment by ben-mkiv** [comment]
Here's a prebuild of 2.1.0 which includes a terminal card, and allows the terminal block to be used as upgrade in tablets/robots/drones,...

https://github.com/StarChasers/OCGlasses/releases/tag/inb4release

**Comment by ben-mkiv** [comment]
2.1.1 is on curseForge now (which includes the changes)
https://minecraft.curseforge.com/projects/openglasses2/files/2729855
