### ISSUE TITLE
Open Glasses Card? [Suggestion]

### ISSUE THREAD

**Issue by ComputerErika** [StarChasers/OCGlasses#57]
I feel like there should be a card that can connect to the glasses that way I can put it in a tablet and do some stuff with that, altho that would mean you would need to redo the binding of the glasses to the computer... Still, it would be really nice. :) Great mod!

**Comment by ben-mkiv** [comment]
will be done in one of the next releases

**Comment by ComputerErika** [comment]
Thank you :)
