### ISSUE TITLE
Add a method to get a Translation

### ISSUE THREAD

**Issue by xiaC4ll** [StarChasers/OCGlasses#58]
So users can get position of 2D and 3D widgets
(or, if it's possible through widget.getModifiers(), tell me how)

**Comment by ben-mkiv** [comment]
yes you can query the modifiers to get a list of all translations, but once you add a rotation/scale in between it wouldn't be sufficient to sum them up as the rotation/scale affects the the translations after it.

future releases may support the getRenderPosition() method, but for current builds it would always return 0,0,0 as its not finished yet.

**Comment by ben-mkiv** [comment]
fixed in this dev build
https://github.com/StarChasers/OCGlasses/releases/tag/inb4release

**Comment by ben-mkiv** [comment]
2.1.1 is on curseForge now (which includes the changes)
https://minecraft.curseforge.com/projects/openglasses2/files/2729855
