### ISSUE TITLE
Server Crash when client joins with different version

### ISSUE THREAD

**Issue by Shazuli** [StarChasers/OCGlasses#63]
***Hi***

I and a few friends have a server we play on. It appears that if a player logs in with a different version of OG2 the whole server crashes.

<details><summary>crash-server</summary><p>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-90-2823-core.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.1.6+build31-universal.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.2756.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/25/19 4:23 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.bymarcin.openglasses.surface.OCServerSurface.getStats(OCServerSurface.java:151)
	at com.bymarcin.openglasses.surface.OCServerSurface.unsubscribePlayer(OCServerSurface.java:111)
	at com.bymarcin.openglasses.event.minecraft.server.ServerEventHandler.onPlayerLeave(ServerEventHandler.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_356_ServerEventHandler_onPlayerLeave_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:580)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:388)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:792)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:527)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-51-generic
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1669884728 bytes (1592 MB) / 2299002880 bytes (2192 MB) up to 3679977472 bytes (3509 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2840 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version          | Source                                                        | Signature                                |
	|:------ |:-------------------- |:---------------- |:------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2           | minecraft.jar                                                 | None                                     |
	| LCHIJA | mcp                  | 9.42             | minecraft.jar                                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99        | forge.jar                                                     | None                                     |
	| LCHIJA | forge                | 14.23.5.2840     | forge.jar                                                     | None                                     |
	| LCHIJA | opencomputers|core   | 1.7.4.2756       | minecraft.jar                                                 | None                                     |
	| LCHIJA | jei                  | 4.15.0.269       | jei_1.12.2-4.15.0.269.jar                                     | None                                     |
	| LCHIJA | immersiveengineering | 0.12-90-2823     | ImmersiveEngineering-0.12-90-2823.jar                         | None                                     |
	| LCHIJA | alternatingflux      | 0.12.2-1         | alternatingflux-0.13.2-1.jar                                  | None                                     |
	| LCHIJA | aroma1997core        | 2.0.0.2.b165     | Aroma1997Core-1.12.2-2.0.0.2.b165.jar                         | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackup          | 3.0.0.0.b117     | AromaBackup-1.12.2-3.0.0.0.b117.jar                           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackuprecovery  | 3.0.0.0.b117     | AromaBackup-1.12.2-3.0.0.0.b117.jar                           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | quark                | r1.5-146         | Quark-r1.5-146.jar                                            | None                                     |
	| LCHIJA | autoreglib           | 1.3-26           | AutoRegLib-1.3-26.jar                                         | None                                     |
	| LCHIJA | bbor                 | 1.0.3            | BBOutlineReloaded-1.0.3-1.12.2-forge.jar                      | None                                     |
	| LCHIJA | bibliocraft          | 2.4.5            | BiblioCraft[v2.4.5][MC1.12.2].jar                             | None                                     |
	| LCHIJA | cfm                  | 6.2.0            | cfm-6.2.0-mc1.12.2.jar                                        | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353        | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks        | 2.4.1.73         | ChickenChunks-1.12.2-2.4.1.73-universal.jar                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | asielib              | 1.0.0            | Computronics-1.12.1-1.6.5.jar                                 | None                                     |
	| LCHIJA | opencomputers        | 1.7.4.2756       | OpenComputers-MC1.12.2-1.7.4.2756.jar                         | None                                     |
	| LCHIJA | tis3d                | 1.5.1.37         | TIS-3D-MC1.12.2-1.5.1.37.jar                                  | None                                     |
	| LCHIJA | computronics         | 1.6.5            | Computronics-1.12.1-1.6.5.jar                                 | None                                     |
	| LCHIJA | davidscommands       | 0.1              | DavidsCommands-0.1.jar                                        | None                                     |
	| LCHIJA | com.boydti.fawe      | 3.5.1            | FastAsyncWorldEdit-forge112-19.03.29-d13b946-1257-22.0.14.jar | None                                     |
	| LCHIJA | flatcoloredblocks    | mc1.12-6.6       | flatcoloredblocks-mc1.12-6.6.jar                              | None                                     |
	| LCHIJA | gravestone           | 1.10.2           | gravestone-1.10.2.jar                                         | None                                     |
	| LCHIJA | immersivepetroleum   | 1.1.8            | immersivepetroleum-1.12.2-1.1.8.jar                           | None                                     |
	| LCHIJA | laggoggles           | FORGE-1.12.2-4.1 | LagGoggles-FORGE-1.12.2-4.1.jar                               | None                                     |
	| LCHIJA | lightningtweaks      | 1.12.2-1.2.1.0   | lightningtweaks-1.12.2-1.2.1.0.jar                            | None                                     |
	| LCHIJA | lunatriuscore        | 1.2.0.42         | LunatriusCore-1.12.2-1.2.0.42-universal.jar                   | None                                     |
	| LCHIJA | morefood             | 1.18             | morefood-1.19.jar                                             | None                                     |
	| LCHIJA | guitoolkit           | 1.0.3            | OpenGlasses-MC1.12.2-2.1.0.jar                                | None                                     |
	| LCHIJA | rendertoolkit        | 1.0.3            | OpenGlasses-MC1.12.2-2.1.0.jar                                | None                                     |
	| LCHIJA | openglasses          | 2.1.0            | OpenGlasses-MC1.12.2-2.1.0.jar                                | None                                     |
	| LCHIJA | openprinter          | 0.1.0.2          | OpenPrinter-1.12.2-0.1.0.2.jar                                | None                                     |
	| LCHIJA | rsgauges             | 1.1.4            | rsgauges-1.12.2-1.1.4.jar                                     | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | schematica           | 1.8.0.169        | Schematica-1.12.2-1.8.0.169-universal.jar                     | None                                     |
	| LCHIJA | thutcore             | 5.19.9           | thutcore-1.12.2-5.19.9.jar                                    | None                                     |
	| LCHIJA | thutcore_compat      | 1.0              | thutcore-1.12.2-5.19.9.jar                                    | None                                     |
	| LCHIJA | thuttech             | 6.1.5            | thuttech-1.12.2-6.1.5.jar                                     | None                                     |
	| LCHIJA | tickprofiler         | 1.12-0.0.7       | TickProfiler-1.12-0.0.7.jar                                   | None                                     |
	| LCHIJA | tickratechanger      | 1.0.14           | TickrateChanger-1.0.14.jar                                    | None                                     |
	| LCHIJA | worldedit            | 6.1.10-SNAPSHOT  | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar             | None                                     |
	| LCHIJA | phosphor-lighting    | 1.12.2-0.1.6     | phosphor-1.12.2-0.1.6+build31-universal.jar                   | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-90-2823-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.1.6+build31-universal.jar)
  
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.2756.jar)
  li.cil.oc.common.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 100; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
</p></details>

**Comment by ben-mkiv** [comment]
thanks for the quick report, fixed the issue in 2.1.1-1
https://minecraft.curseforge.com/projects/openglasses2/files/2730035
