### ISSUE TITLE
Openglasses incompatible with Bungeecord

### ISSUE THREAD

**Issue by ghost** [StarChasers/OCGlasses#64]
Glasses don't render text or send messages to a computer when a user is connected via bungeecord. There is no log errors, or information otherwise.

**Comment by ben-mkiv** [comment]
can you please try if turning off the glasses and putting them back on after logging in does fix the issue?

**Comment by ghost** [comment]
Yeah, I've tried that, I believe it may have something to do with bungee not transmitting the packets across.
So far glasses work fine without the proxy, adding the proxy breaks them again.
This is the only mod in my pack affected by this so far.

**Comment by ghost** [comment]
I've tried logging off/logging back in, no effect

**Comment by ben-mkiv** [comment]
Thanks, i'll have to look into that later, as i've never used BungeeCord before and i have no idea how to set it up. If your modpack doesnt have a ton of mods and you would share the ip with me, i could try to debug it client side.
you can bug me on [Discord](https://discordapp.com/invite/8FCFdCK) if you dont want to post server details here

**Comment by ben-mkiv** [comment]
fixed in 2.1.1-6
