### ISSUE TITLE
getUserLookingAt returns nil on server

### ISSUE THREAD

**Issue by djpadbit** [StarChasers/OCGlasses#67]
Title says it all, when running the getUserLookingAt on a server it returns nil. The glasses have all the upgrades required to be able to use the function.
![2019-07-03_23 03 51](https://user-images.githubusercontent.com/9431263/60625158-46107280-9de7-11e9-8dd8-0cbf2433bdca.png)

Opencomputer version: 1.7.4.153
Openglasses version: 2.1.1-6
Forge version: 14.23.5.2836

As a side note, even though it's the second issue i post today, i really enjoy the mod and i think it's really cool. Keep up the good work.

**Comment by ben-mkiv** [comment]
thanks for reporting this issue. The next release will have that fixed. Also every bug report is appreciated :)

you can grab a prebuild here:
http://ci.pc-logix.com/job/OCGlasses/13/artifact/build/libs/OpenGlasses-MC1.12.2-2.1.1-13.jar

**Comment by ben-mkiv** [comment]
fixed build is now also on curseForge
https://www.curseforge.com/minecraft/mc-mods/openglasses2/files
