### ISSUE TITLE
addColor method doesn't correctly verify parameters

### ISSUE THREAD

**Issue by Faeranne** [StarChasers/OCGlasses#68]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2768
Java Version: 11.0.1 2018-10-16 LTS
OCGlasses Version: 2.1.1-6

When using `addColor`, if you input any value over 1, it causes a crash with the error "Color parameter outside of expected range".  This crash persists when reloading the world.  The only fix I have found so far is to reload the world without the OCGlasses mod.

**Comment by ben-mkiv** [comment]
thanks for reporting this issue. The next release will limit the values to 0-1

you can grab a prebuild here:
http://ci.pc-logix.com/job/OCGlasses/13/artifact/build/libs/OpenGlasses-MC1.12.2-2.1.1-13.jar

**Comment by Faeranne** [comment]
Looks like it's fixed as of 2.1.1-13.
