### ISSUE TITLE
startLinking incorrectly uses EntityPlayerSP in singleplayer worlds

### ISSUE THREAD

**Issue by Faeranne** [StarChasers/OCGlasses#69]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2768
Java Version: 11.0.1 2018-10-16 LTS
OCGlasses Version: 2.1.1-17

When using the command `startLinking` and passing a username, the command responds with `net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.client.entity.EntityPlayerMP` and fails.  Seems to be related to how `getPlayer` in the clientproxy fetches the player.

When used in a server, everything works as expected.

**Comment by ben-mkiv** [comment]
thanks for the report, here is a fixed version
http://ci.pc-logix.com/job/OCGlasses/18/artifact/build/libs/OpenGlasses-MC1.12.2-2.1.1-18.jar

**Comment by Faeranne** [comment]
Looks like it works!
You have really been knocking these fixes out of the park.  Thanks for the dedication!
