### ISSUE TITLE
Widgets stop rendering when setOwner is used

### ISSUE THREAD

**Issue by Faeranne** [StarChasers/OCGlasses#70]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2768
Java Version: 11.0.1 2018-10-16 LTS
OCGlasses Version: 2.1.1-18

When using `setOwner` on any widget, it stops being rendered regardless of what the owner is set to.  This happens on both in Single Player and on Servers.

**Comment by ben-mkiv** [comment]
thanks much for the bugreport, issue should be fixed in this build, but requires you to relink your glasses as i've forgotten to save some data on the glasses while linking O:-)

http://ci.pc-logix.com/job/OCGlasses/22/artifact/build/libs/OpenGlasses-MC1.12.2-2.1.1-22.jar

**Comment by ben-mkiv** [comment]
fixed build is now also on curseForge
https://www.curseforge.com/minecraft/mc-mods/openglasses2/files
