### ISSUE TITLE
[Bug] Thermal Vision not available after installing all possible upgrades

### ISSUE THREAD

**Issue by shadoxxhd** [StarChasers/OCGlasses#73]
**Describe the bug**
I installed all available upgrades (only one energy upgrade 3, everything else maxed), but thermal vision is still marked as not available.

**In which environment did the Bug appear?**
Singleplayer Enigmatica 2: Expert with manually added computronics and OCGlasses

**To Reproduce**
1. craft OC glasses
2. add all upgrades via anvil (I started with the tank upgrade, then an energy upgrade 3, then 2* DB1, 3*DB2, 2*DB3 (adds to exactly 255 widget count), then started adding the remaining upgrades in the order they appear in on the wiki page)
3. every update shows as installed, except thermal vision (even though it doesn't list any unfulfilled requirements, see image).

**Expected behavior**
Thermal Vision is shown as 'available'.

**Screenshots / Code Snippet**
<img src="https://i.imgur.com/llskrSP.png">

**Minecraft:**
 - Mod Version: 2.2-25
 - Minecraft Version: 1.12
 - Forge Version: 14.23.5.2781

**Comment by ben-mkiv** [comment]
leaving this open until official release is on CF

**Comment by ben-mkiv** [comment]
version 2-2.2-36 is now on curseForge, which includes a fix
