### ISSUE TITLE
[Bug] Black Screen w/ OptiFine Fast Render

### ISSUE THREAD

**Issue by nephatrine** [StarChasers/OCGlasses#78]
**Describe the bug**
In version OpenGlasses-MC1.12.2-2.2-36.jar when using OptiFine, I did not experience any issues except that the thermal vision did not work (caused black screen). When I updated to OpenGlasses-MC1.12.2-2.2-38.jar (which boasted improvements to OptiFine support in the changelog), I was greeted with a black screen regardless of whether I was even wearing the glasses at all and even in a brand new world. The only way to resolve this was disabling Fast Render in the OptiFine settings. While I can personally live with disabling fast render, some users may need fast render for one reason or another and I'd imagine thermal vision not working was an acceptable trade-off compared to the game being literally unplayable.

**In which environment did the Bug appear?**
Both singleplayer as well as connected to server.

**To Reproduce**
 - Update OpenGlasses2.
 - Use Optifine Fast Render.
 - Start game, load game, whatever.
 - See nothing but the black abyss.

**Expected behavior**
See the game, at least when not actively using visual effects like thermal vision that are expected to have issues with OptiFine.

**Minecraft:**
 - OpenGlasses-MC1.12.2-2.2-38
 - Minecraft Minecraft 1.12
 - forge-1.12.2-14.23.5.2838
 - OptiFine-1.12.2_HD_U_E3

**Comment by ben-mkiv** [comment]
Sorry for the inconvenience and thanks for reporting the issue.

Here's a test version which should fix the issue, but i have to test it further in the next days before uploading it to curseForge. (You also need Commons0815 1.3.2 from the 2nd link)

The Thermal Vision *should* work now with FastRender, too

http://ci.pc-logix.com/job/OCGlasses/40/artifact/build/libs/OpenGlasses-MC1.12.2-2.2-40.jar
https://www.curseforge.com/minecraft/mc-mods/commons0815/files/2810553

**Comment by nephatrine** [comment]
Sorry, it's been a busy week and did not get around to testing that version until just now. I wouldn't have normally even reported anything in the first place if there wasn't a regression from the previous version since I know mod authors hate trying to accommodate optifine's hackery.

Using the -40 version, I can see again both with and without the glasses. The thermal vision still just gives a black screen though. I don't care too much about that ~~as people who want to use it can just toggle off fast render~~ (EDIT: actually thermal vision now doesn't work even with fast render disabled even though it did with version 38).

**Comment by ben-mkiv** [comment]
everything should be fixed in 2.2-41 which is on curseForge now

**Comment by nephatrine** [comment]
Maybe I've just got a strange compatibility issue then because -41 is back to everything being black again regardless of fast render or whether using the glasses.

**Comment by ben-mkiv** [comment]
edit: just tested, yea i messed that up... sorry again. I'll take a look tomorrow

**Comment by ben-mkiv** [comment]
2.2-42 is on curseForge now (also Commons0815 should be updated to 1.3.4)
Hope this time everything works as expected...

**Comment by nephatrine** [comment]
Everything works perfectly. Thanks so much. Sorry for being a pain.
