### ISSUE TITLE
[Bug] DSHuds Issue Latest Version

### ISSUE THREAD

**Issue by nephatrine** [StarChasers/OCGlasses#79]
**Describe the bug**
When updating to OpenGlasses-MC1.12.2-2.2-38 or greater, the light display and chunk borders from [Dynamic Surroundings: HUDs](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-huds) are not visible anymore. It works with the previous OpenGlasses-MC1.12.2-2.2-25 though.

**Minecraft:**
 - OpenGlasses-MC1.12.2-2.2-38
 - forge-1.12.2-14.23.5.2838
 - DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA

**Additional context**
I am using OptiFine as well. OptiFine settings did not appear to have any effect on this regression, though I have not yet tested whether issue occurs without OptiFine so it may be a contributing factor.

**Comment by ben-mkiv** [comment]
everything should be fixed in 2.2-41 which is on curseForge now

also get sure to update commons0815 lib

**Comment by ben-mkiv** [comment]
Closing this as there wasn't any feedback, feel free to open a new bug report referencing to this if the issue persists for you or comes up again.
