### ISSUE TITLE
[Bug] addVertex function returns nil

### ISSUE THREAD

**Issue by i3ym** [StarChasers/OCGlasses#81]
The wiki says that addVertex function should return vertex's index, but it returns nil

**Comment by ben-mkiv** [comment]
thanks for reporting the issue. do you have an example script which i can use to test my fix approach?

if you want to test yourself, heres the build:
http://ci.pc-logix.com/job/OCGlasses/45/artifact/build/libs/OpenGlasses-MC1.12.2-2.2-45.jar

requires commons0815-1.3.5 which you can grab here:
https://github.com/StarChasers/OCGlasses/raw/OG2-MC1.12.2/libs/Commons0815-1.12.2-1.3.5.jar

**Comment by i3ym** [comment]
Tested with the following code:
```
glasses = require("component").glasses;
tr = glasses.addCustom2D();
for i = 1, 20 do
  index = tr.addVertex(0, 0, 0);
  print(index);
end
```

Now works perfectly
![image](https://user-images.githubusercontent.com/20320769/68933387-217dcb80-07c7-11ea-969f-63f66ce6e59a.png)
