### ISSUE TITLE
[Bug] setVertex function adds a new vertex

### ISSUE THREAD

**Issue by i3ym** [StarChasers/OCGlasses#82]
![image](https://user-images.githubusercontent.com/20320769/68948949-98c55680-07eb-11ea-9f74-7fbd3eda4606.png)

**Comment by ben-mkiv** [comment]
fixed in this build
http://ci.pc-logix.com/job/OCGlasses/46/artifact/build/libs/OpenGlasses-MC1.12.2-2.2-46.jar
