### ISSUE TITLE
[Bug] Thermal vision makes game crash

### ISSUE THREAD

**Issue by i3ym** [StarChasers/OCGlasses#83]
OpenComputers v1.7.4.153
OpenGlasses v2.2-46
Commons0815 v1.3.5

When I turn on thermal vision the game turns green for a second and then crashes:
https://pastebin.com/v2h1gx1M

When I try to join this world game immediately crashes but with another crash-report:
https://pastebin.com/cXvjW2Ly

**Comment by ben-mkiv** [comment]
Thanks for the notice :)

The issue was in commons0815 lib, fixed file is here:
https://github.com/StarChasers/OCGlasses/blob/OG2-MC1.12.2/libs/Commons0815-1.12.2-1.3.6.jar
