### ISSUE TITLE
[Bug] glasses сharging

### ISSUE THREAD

**Issue by gosha2** [StarChasers/OCGlasses#85]
**Describe the bug**
Crafted glasses cant charge.
[movie](https://yadi.sk/i/GC8I0eQDpbVFoA)
Wiki haven't  information about this initialisation part.

**Minecraft:**
 - Mod Version (OpenGlasses-MC1.12.2-2.2-36)
 - Minecraft Version (Minecraft 1.12.2)
 - Forge Version (Forge 14.23.5.2847)

**Comment by ben-mkiv** [comment]
thanks for the report. It's fixed in version 2.2-50 which is on curseForge now
