### ISSUE TITLE
[Bug] Mobs in Thermal Vision becomes invisible

### ISSUE THREAD

**Issue by kappa-maintainer** [StarChasers/OCGlasses#86]
**Describe the bug**
Toggling Thermal Vision on just make background blue and all mobs invisible.
**In which environment did the Bug appear?**
Singleplayer, with just OpenGlasses and it's dependency.

**To Reproduce**
1. Install latest forge and latest OpenGlasses
2. Create new superflat world, get AR Glasses from creative tab
3. Put it on helmet slot, toggle thermal vision on

**Expected behavior**
See correct Thermal Vision, which highlight all mobs.
**Screenshots / Code Snippet**
![2019-12-11_15 47 49](https://user-images.githubusercontent.com/11038263/70602061-809bf800-1c2e-11ea-8eaa-721f763a487c.png)
![2019-12-11_15 47 47](https://user-images.githubusercontent.com/11038263/70602087-898cc980-1c2e-11ea-8161-12fa001015ec.png)

**Minecraft:**
 - OpenComputers-MC1.12.2-1.7.5.192
 - OpenGlasses-MC1.12.2-2.2-44
 - Minecraft 1.12.2
 - Forge 14.23.5.2874

**Comment by ben-mkiv** [comment]
thanks for the report. It's fixed in version 2.2-50 which is on curseForge now
