### ISSUE TITLE
[Bug] Text2D disappeared when changed to absolute rendering

### ISSUE THREAD

**Issue by portalmk2** [StarChasers/OCGlasses#88]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2821
Java Version: openjdk version "1.8.0_212" (openj9)
OCGlasses Version: 2.2-50

Calling glasses.setRenderPosition("absolute") makes text2D widgets disappear. Changing to "relative" will bring them back.

> local gt = require("component").glasses
> local txt1 = gt.addText2D()
> txt1.addTranslation(30,30,0)
> txt1.setText("TEST")
> gt.setRenderPosition("absolute")

or setRenderPosition first

> local gt = require("component").glasses
> gt.setRenderPosition("absolute")
> local txt1 = gt.addText2D()
> txt1.addTranslation(30,30,0)
> txt1.setText("TEST")

**Comment by ben-mkiv** [comment]
thanks for reporting the problem. i'll reopen this bug report until theres an official release on curseforge, till then you can use this prebuild:

https://ci.pc-logix.com/job/OCGlasses/55/artifact/build/libs/OpenGlasses-MC1.12.2-2.2-56.jar

**Comment by ben-mkiv** [comment]
official build contains the fix now (however version numbers gone a bit down as the buildbot was set up new, so 53 is newer than the previously linked 56)
https://www.curseforge.com/minecraft/mc-mods/openglasses2/files/3143467
