### ISSUE TITLE
Add configurable total widget limit

### ISSUE THREAD

**Issue by itsmeow** [StarChasers/OCGlasses#90]
**Is your feature request related to a problem? Please describe.**
I want to render lots of things, but I can't because there's a hard limit on the mod itself

**Describe the solution you'd like**
Make the maximum limit configurable. Would also be nice if XP requirements were configurable (I personally dislike the 10/20/30 level XP requirements, so I just give myself the XP)

**Describe alternatives you've considered**
Could just remove the max limit but I feel like that might cause some issues...

**Additional context**
I'm trying to render lots of widgets so I can make all my wires visible through walls

**Comment by ben-mkiv** [comment]
added in dev, build here, limit can be set in minecraft => mods => openglasses => config => general
https://ci.pc-logix.com/job/OCGlasses/59/artifact/build/libs/OpenGlasses-MC1.12.2-2.2-59.jar

**Comment by ben-mkiv** [comment]
official build contains the fix now (however version numbers gone a bit down as the buildbot was set up new, so 53 is newer than the previously linked 59)
https://www.curseforge.com/minecraft/mc-mods/openglasses2/files/3143467
