### ISSUE TITLE
[Bug] AR glasses not rendering in bauble

### ISSUE THREAD

**Issue by CodedSakura** [StarChasers/OCGlasses#93]
**Describe the bug**
AR glasses don't render when in the bauble slot.

**Expected behavior**
AR glasses should render if they are in the bauble slot, like they do when they're in the helmet slot.

**Screenshots / Code Snippet**
![2020-05-22_09 57 56](https://user-images.githubusercontent.com/23125996/82640508-67529b00-9c13-11ea-81da-24d383b495e8.png)

**Minecraft:**
 - Mod Version: OpenGlasses-MC1.12.2-2.2-50
 - Minecraft Version: 1.12.2
 - Forge Version: Forge 14.23.5.2854
 - Baubles Version: Baubles-1.12-1.5.2

**Comment by ben-mkiv** [comment]
probably an issue with your player skin, is that using an overlay for the head? (as it appears pretty big) 

The glasses render closer to the head when equipped as baubles item.

can you either provide a link to your skin, or test with another please?

**Comment by CodedSakura** [comment]
after turning everything off in the skin customization settings, the glasses still do not appear
![2020-06-21_11 22 57](https://user-images.githubusercontent.com/23125996/85220116-bb3ad600-b3b1-11ea-8184-b4c61ca2d7f0.png)

**Comment by ben-mkiv** [comment]
reopened until a public release is available

**Comment by ben-mkiv** [comment]
official build contains the fix now
https://www.curseforge.com/minecraft/mc-mods/openglasses2/files/3143467
